### PR TITLE
Add missing APIs to be enabled in the documentation

### PR DESCRIPTION
**Pull request by estebanbouza**
Added missing APIs that are required when setting up a new environment with the documentation steps.

### CODE REVIEW

**Comment by arora-sagar** [comment]
Hi @efiacor Thanks for this PR. Did you test end to end on GCP? The rest of the content in the document is still valid?

**Comment by liamfallon** [comment]
Hi @estebanbouza , would you be able to look into the CLA? Once that's done, we can merge this PR.

**Comment by efiacor** [comment]
https://github.com/nephio-project/docs/pull/197

**Pull request closed without merging**
