### PR TITLE
Add version support for R3

### PR DESCRIPTION
**Pull request by CsatariGergely**
Partially fixes: https://github.com/nephio-project/nephio/issues/738

### CODE REVIEW

**Comment by liamfallon** [comment]
When I click R3 on the releases dropdown tab, and go to the "R3" page, the releases dropdown disappears, see below.
Screenshot 2024-06-17 at 15 09 32

See below:

Screenshot 2024-06-17 at 15 09 42

**Comment by CsatariGergely** [comment]
> When I click R3 on the releases dropdown tab, and go to the "R3" page, the releases dropdown disappears, see below. Screenshot 2024-06-17 at 15 09 32
> 
> See below:
> 
> Screenshot 2024-06-17 at 15 09 42

Haha, yes, that is a chicken and egg problem. When you click the R3 in the drop-down you get to the deployed R3 documentation and that does not have the drop-down yet because this pr is not merged :)

**Comment by liamfallon** [comment]
> > When I click R3 on the releases dropdown tab, and go to the "R3" page, the releases dropdown disappears, see below. Screenshot 2024-06-17 at 15 09 32
> > See below:
> > Screenshot 2024-06-17 at 15 09 42
> 
> Haha, yes, that is a chicken and egg problem. When you click the R3 in the drop-down you get to the deployed R3 documentation and that does not have the drop-down yet because this pr is not merged :)

OK, that's fine.

**Pull request merged**
