### PR TITLE
Update OpenStack installation with the overriding method

### PR DESCRIPTION
**Pull request by electrocucaracha**

### CODE REVIEW

**Review by lapentad — COMMENTED** [review]
Hi Victor, I am getting an error parsing the VCPU

TASK [bootstrap : Checking host has minimum number of CPUS] ********************
Tuesday 28 November 2023  10:23:11 +0000 (0:00:00.052)       0:00:39.916 ******
Tuesday 28 November 2023  10:23:11 +0000 (0:00:00.052)       0:00:39.915 ******
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'ansible_facts.processor_vcpus >= host_min_vcpu' failed. The error was: Unexpected templating type error occurred on ({% if ansible_facts.processor_vcpus >= host_min_vcpu %} True {% else %} False {% endif %}): '>=' **not supported between instances of 'int' and 'str'**"}

**Comment by electrocucaracha** [comment]
> Hi Victor, I am getting an error parsing the VCPU
> 
> TASK [bootstrap : Checking host has minimum number of CPUS] ******************** Tuesday 28 November 2023 10:23:11 +0000 (0:00:00.052) 0:00:39.916 ****** Tuesday 28 November 2023 10:23:11 +0000 (0:00:00.052) 0:00:39.915 ****** fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'ansible_facts.processor_vcpus >= host_min_vcpu' failed. The error was: Unexpected templating type error occurred on ({% if ansible_facts.processor_vcpus >= host_min_vcpu %} True {% else %} False {% endif %}): '>=' **not supported between instances of 'int' and 'str'**"}

Interesting, it seems like the value is passed as string, let me try to replicate it in my local environment.

**Comment by electrocucaracha** [comment]
> > Hi Victor, I am getting an error parsing the VCPU
> > TASK [bootstrap : Checking host has minimum number of CPUS] ******************** Tuesday 28 November 2023 10:23:11 +0000 (0:00:00.052) 0:00:39.916 ****** Tuesday 28 November 2023 10:23:11 +0000 (0:00:00.052) 0:00:39.915 ****** fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'ansible_facts.processor_vcpus >= host_min_vcpu' failed. The error was: Unexpected templating type error occurred on ({% if ansible_facts.processor_vcpus >= host_min_vcpu %} True {% else %} False {% endif %}): '>=' **not supported between instances of 'int' and 'str'**"}
> 
> Interesting, it seems like the value is passed as string, let me try to replicate it in my local environment.

I found the issue, I was using the `--extra-vars` Ansible flag in a wrong way, I have submitted the [fix](https://github.com/nephio-project/test-infra/pull/220)

**Comment by CsatariGergely** [comment]
@electrocucaracha  we did a quite big refactoring of the documentation structure. Would you like to update this pr to follow the new structure or is it okay if I reimplement it in a new pr?

**Comment by lapentad** [comment]
Hi @electrocucaracha and @CsatariGergely  I created the new pr https://github.com/nephio-project/docs/pull/81

**Comment by lapentad** [comment]
> Hi @electrocucaracha and @CsatariGergely I created the new pr #81

This pr can be abandoned, because #81 is meant to fix it

**Comment by electrocucaracha** [comment]
Closing this in favor of https://github.com/nephio-project/docs/pull/81

**Pull request closed without merging**
