### PR TITLE
Update kpt alpha to use porchctl

### PR DESCRIPTION
**Pull request by efiacor**

### CODE REVIEW

**Comment by liamfallon** [comment]
Will wait for some more "approves" before doing a "lgtm"

**Comment by liamfallon** [comment]
It'd be good to get one more /approve on this

**Comment by electrocucaracha** [comment]
@efiacor it seems like there is a rebase conflict on this PR, and could you include a `porchctl` as part of the [prerequisites](https://github.com/nephio-project/docs/blob/main/content/en/docs/guides/install-guides/install-on-byoc.md?plain=1#L32)?

**Comment by efiacor** [comment]
> @efiacor it seems like there is a rebase conflict on this PR, and could you include a `porchctl` as part of the [prerequisites](https://github.com/nephio-project/docs/blob/main/content/en/docs/guides/install-guides/install-on-byoc.md?plain=1#L32)?

Done. I will need to update the porch docs to include an install guide asap. Linked to the release page on gh for now. We also need to do an official release as it is still in pre release state.

**Pull request closed without merging**
