### PR TITLE
Moving documentation to Hugo and Docsy

### PR DESCRIPTION
**Pull request by CsatariGergely**
This pr moves the documentation from plain md files rendered in GitHub to [Hugo](https://gohugo.io/) and the [Docsy](https://www.docsy.dev/) theme.

The plan is to get the documentation published on Netifly and assign https://docs.nephio.org with the end result.

The source branch is rendered [here](https://lighthearted-mermaid-d18bb0.netlify.app/)

TODO: 
- Review the files for broken links, pictures and straightforward language issues
- Collect feedback on the structure

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@gvbalaji here is the draft pr for the move to Hugo.

I think we should still need to clarify some structural issues:
1) I think we should remove the "cover page". It does not add too match to the documentation, but users need to click and extra click to get to the documents. It is there as it is part of the Docsy template.
2) Now we have a "Guides" section what contains the install, user and contributor guides. Maybe we do not need to have this level.
3) There are lots of text in the root of the [Nephio Install Guides](https://lighthearted-mermaid-d18bb0.netlify.app/docs/guides/install-guides/) section. I have a feeling that maybe we should move this to an own file.
4) I tried to order the install guides into a logical order, but I'm not sure if this is the correct order
5) [Nephio User Guides](https://lighthearted-mermaid-d18bb0.netlify.app/docs/guides/install-guides/) has also lots of text, what maybe should go to a separate file

**Comment by johnbelamaric** [comment]
This is totally awesome! Great job. The rendered site looks excellent.

How will this work once it merges, as far as where/how we update the docs, and how they get compiled and up and running on the docs site?

/approve

**Comment by johnbelamaric** [comment]
I wonder if the current nephio.org/learn pages should move to this instead of the wiki?

**Comment by CsatariGergely** [comment]
> This is totally awesome! Great job. The rendered site looks excellent.

Thanks. There are still a couple of things what we would like to fix, but I think it is a good start. 

> How will this work once it merges, as far as where/how we update the docs, and how they get compiled and up and running on the docs site?

We keep updating the docs in this repo, but we will need to add some hugo specific annotations to the .md files we create. They are compiled and hosted by Netifly automatically. 
At the moment this site is connected to the branch in the Nokia fork of the repo and rendered automatically: https://hugo-docs--lighthearted-mermaid-d18bb0.netlify.app/

What we will need to do after the merge: 
* Connect the build to the main branch of this repo
* Use a redirect of docs.nephio.com to the url of the site
* Register Nephio at Netifly as an open source project
* Build some kind of automation to check if the hugo build is successful for the pr-s.

**Comment by gvbalaji** [comment]
This looks great. Thanks @CsatariGergely 
/approve

**Pull request merged**
