### PR TITLE
Adding myself as a reviewer

### PR DESCRIPTION
**Pull request by CsatariGergely**

### CODE REVIEW

**Comment by liamfallon** [comment]
@CsatariGergely I wonder if you can ask to be added as a member of Nephio?

**Comment by CsatariGergely** [comment]
> you can ask to be added as a member of Nephio?

Sure, how do I do that?

**Comment by liamfallon** [comment]
> > you can ask to be added as a member of Nephio?
> 
> Sure, how do I do that?

I think the owner of the Github organization has to do it. @henderiw , @tliron , or @johnbelamaric would know.

**Comment by radoslawc** [comment]
@CsatariGergely we have a suspicion that this PR might be confusing PROW's merging system, I'll close it for now, if it's not that it can be reopened.

**Pull request closed without merging**
