### PR TITLE
Removed hidden code outputs

### PR DESCRIPTION
**Pull request by lovesprung**
Fixes: https://github.com/nephio-project/nephio/issues/495

### CODE REVIEW

**Comment by lovesprung** [comment]
What does the "invalid-commit-message" tag mean? What should I change/add?

**Comment by CsatariGergely** [comment]
I'm working on fixing the build.

**Comment by radoslawc** [comment]
Hi @lovesprung 

[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

If you accidentally used `fixes #NNNN` or @-mention, you need to rewrite the git history
of your branch to remove the `do-not-merge/invalid-commit-message` label. 
See [Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Comment by lovesprung** [comment]
Thanks @radoslawc , it's fixed now :)

**Comment by lovesprung** [comment]
@liamfallon @efiacor the build is fixed, please check.

**Pull request merged**
