### PR TITLE
updated doc to call out docker supplementary group is loaded

### PR DESCRIPTION
**Pull request by vjayaramrh**
closes: https://github.com/nephio-project/nephio/issues/589

### CODE REVIEW

**Comment by vjayaramrh** [comment]
@radoslawc Wondering why the EasyCLA does not have a green check mark yet?
cc: @electrocucaracha @liamfallon

**Comment by liamfallon** [comment]
> @radoslawc Wondering why the EasyCLA does not have a green check mark yet? cc: @electrocucaracha @liamfallon

I wondered about that as well. That check should be automatic.

**Review by liamfallon — COMMENTED** [review]
Looks good.

**Pull request merged**
