### PR TITLE
Adding versioning support

### PR DESCRIPTION
**Pull request by CsatariGergely**
This change adds a menu to the documentation pointing to the different versions of the deployed documentation set.

Partly fixes [#738](https://github.com/nephio-project/nephio/issues/738)

### CODE REVIEW

**Review by efiacor — COMMENTED** [review]
Not sure how to fix it but the breadcrumbs nav on the R2/3 versions give a 404

Screenshot from 2024-06-06 10-58-37

Screenshot from 2024-06-06 11-00-05

**Review by liamfallon — COMMENTED** [review]
OK with me once the comment from @efiacor is resolved.

**Comment by CsatariGergely** [comment]
> Not sure how to fix it but the breadcrumbs nav on the R2/3 versions give a 404
> 
> Screenshot from 2024-06-06 10-58-37
> 
> Screenshot from 2024-06-06 11-00-05

Uh-oh good catch. This is an issue with the base url setting. I've created separate pr-s for fixing those.
https://github.com/nephio-project/docs/pull/135
https://github.com/nephio-project/docs/pull/136

**Comment by liamfallon** [comment]
For me this needs docsy 0.10.0, but once that's done, this is working. See https://github.com/nephio-project/docs/pull/137

**Pull request merged**
